spring:
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/workshop
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true